name: preference_list
description: Simplifies building preference pages with flexibility and ease-of-use.
version: 0.0.2
homepage: https://github.com/leanflutter/preference_list

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  influxui: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mostly_reasonable_lints: ^0.1.1
